# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20191027_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-profile_picture']},
        ),
    ]
